# kuri Theme Config @ version 1.0.0
# website: https://kuri.ink | cl@kuri.ink

# Yourself / 个人信息
nickname:  制霸蛋餅統天下
motto: 哈摟你好嗎
logo:  https://i.postimg.cc/Zqc0GN9T/tou-tie.jpg
github:  https://github.com/fyc970823
background: # 背景图片
  - https://i.postimg.cc/PqRNfj4s/images.jpg
iconfont: /css/iconfont.css

# SEO / 搜索引擎优化
fav: /images/fav.png

# Sidebar / 侧边栏
sidebar:
  導航: # 类别名称
    一起搖滾: # 项目名称
      - https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1 # 超链接
      - 一起搖滾 # MDUI 鼠标悬停工具提示
    作者IG:
      - https://www.instagram.com/fyc_1940/
      - 作者IG

sidebar_color: 
  導航: # 类别名称
    - near_me # 图标
    - mdui-text-color-blue # 图标颜色

# Header / 页眉信息
chizaobook: true # true / false 在页眉显示摛藻好句功能

# Social / 社交按钮
social:
  C1: # 项目名称
    - https://github.com/fyc970823 # 超链接
    - 關於我 # MDUI 鼠标悬停工具提示
    - iconfont iconaboutme # 图标
  C2: 
    - https://github.com/fyc970823
    - 照片
    - iconfont iconcarema
  C3:
    - https://github.com/fyc970823
    - 友站
    - iconfont iconlink
  C4:
    - https://github.com/fyc970823
    - 信箱
    - iconfont iconemail


# Footer / 页脚信息
## copyright / 版权
author:  # 作者名称
## remark / 备注
remark: ''
## Regist / 备案
regist: ''

# tools / 工具
analysis: 
  platform: 51.la
  id: 
  cd: 
aplayer: 
  enable: false
  platform: 
  type: 
  id: 
  fixed: true